# Exploring Los Angeles For New Home Buyers

## Introduction & Background

### Los Angeles is the most populous city in California, the second most populous city in the United States, after New York City, and the third most populous city in North America. With an estimated population of nearly four million,Los Angeles is the cultural, financial, and commercial center of Southern California. The city is known for its Mediterranean climate, ethnic diversity, Hollywood, the entertainment industry, and its sprawling metropolis. Los Angeles is the largest city on the West Coast of North America.

### This Analysis is used to explore the amenities for New Home Buyers around Los Angeles. Made it very simple exploring schools, parks, college and Hotels etc.,

## Data Description

### The data used in this project is provided by Foursquare location data. The data are grouped by all information about restaurants, cafes, and stores which in the Los Angeles Area.

## Import Libraries

In [1]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

!pip install geopy

#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

Requirement already satisfied: geopy in c:\users\p ashish\anaconda3\lib\site-packages (1.20.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\p ashish\anaconda3\lib\site-packages (from geopy) (1.49)
Libraries imported.

## FOUR SQUARE CREDENTIALS

In [2]:
ClIENT_ID = '4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0' # your Foursquare ID
ClIENT_SECRET = 'RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ' # your Foursquare Secret
VERSION = '20180604'
LIMIT =30
print('Your credentails:')
print('Foursquare_ID: ' + ClIENT_ID)
print('Foursquare_Secret:' + ClIENT_SECRET)

Your credentails:
Foursquare_ID: 4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0
Foursquare_Secret:RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ

## Getting the Latitude & Longitude for Los Angeles

In [3]:
city = 'Los Angeles'
geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(city)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

34.0536909 -118.2427666

## Query for Hotel

In [4]:
search_query = 'Hotel'
radius = 500

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0&client_secret=RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ&ll=34.0536909,-118.2427666&v=20180604&query=Hotel&radius=500&limit=30'

In [5]:
results = requests.get(url).json()

In [6]:
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",False,4a47ab0ff964a520eca91fe3,328 E 1st St,US,Los Angeles,United States,NaN,502,"[328 E 1st St, Los Angeles, CA 90012, United S...","[{'label': 'display', 'lat': 34.04974909864657...",34.049749,-118.240111,NaN,90012,CA,Miyako Hotel,v-1565097825,NaN
1,"[{'id': '4d954b06a243a5684965b473', 'name': 'R...",False,505db930e0e2e3d789c50aeb,The Palm Woods Hotel,US,Los Angeles,United States,Hollywood,86,"[The Palm Woods Hotel (Hollywood), Los Angeles...","[{'label': 'display', 'lat': 34.05403721919709...",34.054037,-118.241923,NaN,90012,CA,The Palm Woods Hotel,v-1565097825,NaN
2,"[{'id': '4c38df4de52ce0d596b336e1', 'name': 'P...",False,4cd50b6876ab721ebce76a6a,120 S Los Angeles St,US,Los Angeles,United States,NaN,352,"[120 S Los Angeles St, Los Angeles, CA 90012, ...","[{'label': 'display', 'lat': 34.050526, 'lng':...",34.050526,-118.242682,NaN,90012,CA,Kyoto Grand Hotel Parking & Gardens Garage,v-1565097825,NaN
3,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",False,4b3d82fff964a520129525e3,200 S Hill St,US,Los Angeles,United States,NaN,483,"[200 S Hill St, Los Angeles, CA 90012, United ...","[{'label': 'display', 'lat': 34.05287006603421...",34.052870,-118.247909,NaN,90012,CA,Kawada Hotel,v-1565097825,NaN
4,"[{'id': '4bf58dd8d48988d129941735', 'name': 'C...",False,4b5113edf964a520314127e3,200 N Spring St,US,Los Angeles,United States,at Temple Ave,35,"[200 N Spring St (at Temple Ave), Los Angeles,...","[{'label': 'display', 'lat': 34.05348417688625...",34.053484,-118.242478,Civic Center,90012,CA,Los Angeles City Hall,v-1565097825,75727220

## Cleaning the Data frame

In [7]:
clean_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')]+ ['id']
clean_dataframe = dataframe.loc[:,clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
clean_dataframe['categories'] = clean_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_dataframe.columns = [column.split('.')[-1] for column in clean_dataframe.columns]

clean_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,neighborhood,postalCode,state,id
0,Miyako Hotel,Hotel,328 E 1st St,US,Los Angeles,United States,NaN,502,"[328 E 1st St, Los Angeles, CA 90012, United S...","[{'label': 'display', 'lat': 34.04974909864657...",34.049749,-118.240111,NaN,90012,CA,4a47ab0ff964a520eca91fe3
1,The Palm Woods Hotel,Residential Building (Apartment / Condo),The Palm Woods Hotel,US,Los Angeles,United States,Hollywood,86,"[The Palm Woods Hotel (Hollywood), Los Angeles...","[{'label': 'display', 'lat': 34.05403721919709...",34.054037,-118.241923,NaN,90012,CA,505db930e0e2e3d789c50aeb
2,Kyoto Grand Hotel Parking & Gardens Garage,Parking,120 S Los Angeles St,US,Los Angeles,United States,NaN,352,"[120 S Los Angeles St, Los Angeles, CA 90012, ...","[{'label': 'display', 'lat': 34.050526, 'lng':...",34.050526,-118.242682,NaN,90012,CA,4cd50b6876ab721ebce76a6a
3,Kawada Hotel,Hotel,200 S Hill St,US,Los Angeles,United States,NaN,483,"[200 S Hill St, Los Angeles, CA 90012, United ...","[{'label': 'display', 'lat': 34.05287006603421...",34.052870,-118.247909,NaN,90012,CA,4b3d82fff964a520129525e3
4,Los Angeles City Hall,City Hall,200 N Spring St,US,Los Angeles,United States,at Temple Ave,35,"[200 N Spring St (at Temple Ave), Los Angeles,...","[{'label': 'display', 'lat': 34.05348417688625...",34.053484,-118.242478,Civic Center,90012,CA,4b5113edf964a520314127e3

## Dropping the Irrelevant Columns

In [8]:
clean_dataframe2= clean_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs','neighborhood', 'id'], axis=1)
clean_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
1,The Palm Woods Hotel,Residential Building (Apartment / Condo),The Palm Woods Hotel,34.054037,-118.241923,90012,CA
2,Kyoto Grand Hotel Parking & Gardens Garage,Parking,120 S Los Angeles St,34.050526,-118.242682,90012,CA
3,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
4,Los Angeles City Hall,City Hall,200 N Spring St,34.053484,-118.242478,90012,CA
5,Hotel Cortez,Hotel,NaN,34.053043,-118.241898,NaN,CA
6,Wyndham Garden Hotel,None,5757 Telegraph Rd,34.053335,-118.243448,90040,CA
7,Roes hotel,Hotel,2683 Euclid Avenue,34.052979,-118.243178,90001,CA
8,Hotel Cafe - 2nd Stage,Music Venue,NaN,34.052234,-118.243685,NaN,CA
9,Kyoto Grand Hotel Garden,Garden,The Kyoto Grand Hotel and Gardens,34.051775,-118.242175,90012,CA
10,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
11,Little Tokyo Hotel,Boarding House,327 1/2 E 1st St,34.049924,-118.240153,90012,CA
12,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA
13,Omni Hotel Hershey Room,Meeting Room,NaN,34.050812,-118.248165,NaN,CA
14,St George Hotel,Government Building,115 E 3rd St Apt 516,34.049488,-118.246138,90013,CA
15,Moe's Bar,Bar,2nd St.,34.050549,-118.242900,90066,CA
16,Arrive Hotels & Resorts International Headquar...,General Travel,NaN,34.051426,-118.248137,90013,CA

In [9]:
clean_dataframe3 = clean_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
1,The Palm Woods Hotel,Residential Building (Apartment / Condo),The Palm Woods Hotel,34.054037,-118.241923,90012,CA
2,Kyoto Grand Hotel Parking & Gardens Garage,Parking,120 S Los Angeles St,34.050526,-118.242682,90012,CA
3,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
4,Los Angeles City Hall,City Hall,200 N Spring St,34.053484,-118.242478,90012,CA
7,Roes hotel,Hotel,2683 Euclid Avenue,34.052979,-118.243178,90001,CA
9,Kyoto Grand Hotel Garden,Garden,The Kyoto Grand Hotel and Gardens,34.051775,-118.242175,90012,CA
10,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
11,Little Tokyo Hotel,Boarding House,327 1/2 E 1st St,34.049924,-118.240153,90012,CA
12,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA
14,St George Hotel,Government Building,115 E 3rd St Apt 516,34.049488,-118.246138,90013,CA
15,Moe's Bar,Bar,2nd St.,34.050549,-118.242900,90066,CA

In [10]:
array= ['Hotel', 'Event Space']
hotel_dataframe= clean_dataframe3.loc[clean_dataframe3['categories'].isin(array)]
hotel_dataframe

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
3,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
7,Roes hotel,Hotel,2683 Euclid Avenue,34.052979,-118.243178,90001,CA
10,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
12,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA

In [11]:
df_hotels = hotel_dataframe.drop_duplicates(subset='name', keep="first")
df_hotels

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
3,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
7,Roes hotel,Hotel,2683 Euclid Avenue,34.052979,-118.243178,90001,CA
10,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
12,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA

In [14]:
hotel_dataframe = df_hotels[df_hotels.postalCode == '90012']
hotel_dataframe

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
3,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
10,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
12,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA

## Query For Schools from FourSquare

In [15]:
search_query = 'Schools'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0&client_secret=RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ&ll=34.0536909,-118.2427666&v=20180604&query=Schools&radius=10000&limit=30'

In [16]:
Sresults = requests.get(url).json()

In [17]:
venues = Sresults['response']['venues']

# tranform venues into a dataframe
School_dataframe = json_normalize(venues)
School_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'id': '5032850891d4c4b30a586d62', 'name': 'C...",False,4bb237b3eb3e952160b9c90a,701 W Cesar E Chavez Ave Ste 204,US,Los Angeles,United States,Grand Avenue,902,[701 W Cesar E Chavez Ave Ste 204 (Grand Avenu...,"[{'label': 'display', 'lat': 34.06127794629281...",34.061278,-118.246224,90012,CA,LA Schools Federal Credit Union,v-1565098272,NaN
1,"[{'id': '4bf58dd8d48988d130941735', 'name': 'B...",False,4d742137d6f06dcbd7b41008,445 S Figueroa St,US,Los Angeles,United States,5th,1333,"[445 S Figueroa St (5th), Los Angeles, CA 9007...","[{'label': 'display', 'lat': 34.05351127205021...",34.053511,-118.257228,90071,CA,KIPP LA Schools (School Support Center),v-1565098272,NaN
2,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",False,4bf1813a1f17ef3bdcf59bc8,250 E 1st St,US,Los Angeles,United States,San Pedro St.,409,"[250 E 1st St (San Pedro St.), Los Angeles, CA...","[{'label': 'display', 'lat': 34.05024149053504...",34.050241,-118.241227,90012,CA,California Charter Schools Association,v-1565098272,NaN
3,"[{'id': '4bf58dd8d48988d13b941735', 'name': 'S...",False,532750fa498ed30bdc6b8fb6,601 S Figueroa St,US,Los Angeles,United States,4th Floor,1567,"[601 S Figueroa St (4th Floor), Los Angeles, C...","[{'label': 'display', 'lat': 34.050896, 'lng':...",34.050896,-118.259423,90017,CA,Alliance College-Ready Public Schools,v-1565098272,NaN
4,"[{'id': '4f4533804b9074f6e4fb0105', 'name': 'E...",False,50228cb6e4b0d34fd036e7a7,NaN,US,Los Angeles,United States,NaN,1186,"[Los Angeles, CA 90071, United States]","[{'label': 'display', 'lat': 34.0530502307586,...",34.053050,-118.255604,90071,CA,Imagine Schools on Superior,v-1565098272,NaN

## Cleaning the School Dataframe

In [18]:
School_clean_columns = ['name', 'categories'] + [col for col in School_dataframe.columns if col.startswith('location.')]+ ['id']
clean_School_dataframe = School_dataframe.loc[:,School_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list1 = row['categories']
    except:
        categories_list1 = row['venue.categories']
        
    if len(categories_list1) == 0:
        return None
    else:
        return categories_list1[0]['name']

# filter the category for each row
clean_School_dataframe['categories'] = clean_School_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_School_dataframe.columns = [column.split('.')[-1] for column in clean_School_dataframe.columns]

clean_School_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,LA Schools Federal Credit Union,Credit Union,701 W Cesar E Chavez Ave Ste 204,US,Los Angeles,United States,Grand Avenue,902,[701 W Cesar E Chavez Ave Ste 204 (Grand Avenu...,"[{'label': 'display', 'lat': 34.06127794629281...",34.061278,-118.246224,90012,CA,4bb237b3eb3e952160b9c90a
1,KIPP LA Schools (School Support Center),Building,445 S Figueroa St,US,Los Angeles,United States,5th,1333,"[445 S Figueroa St (5th), Los Angeles, CA 9007...","[{'label': 'display', 'lat': 34.05351127205021...",34.053511,-118.257228,90071,CA,4d742137d6f06dcbd7b41008
2,California Charter Schools Association,Office,250 E 1st St,US,Los Angeles,United States,San Pedro St.,409,"[250 E 1st St (San Pedro St.), Los Angeles, CA...","[{'label': 'display', 'lat': 34.05024149053504...",34.050241,-118.241227,90012,CA,4bf1813a1f17ef3bdcf59bc8
3,Alliance College-Ready Public Schools,School,601 S Figueroa St,US,Los Angeles,United States,4th Floor,1567,"[601 S Figueroa St (4th Floor), Los Angeles, C...","[{'label': 'display', 'lat': 34.050896, 'lng':...",34.050896,-118.259423,90017,CA,532750fa498ed30bdc6b8fb6
4,Imagine Schools on Superior,Elementary School,NaN,US,Los Angeles,United States,NaN,1186,"[Los Angeles, CA 90071, United States]","[{'label': 'display', 'lat': 34.0530502307586,...",34.053050,-118.255604,90071,CA,50228cb6e4b0d34fd036e7a7

##  Drop the irrelevent columns

In [19]:
# delete unnecessary columns
clean_School_dataframe2= clean_School_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_School_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,LA Schools Federal Credit Union,Credit Union,701 W Cesar E Chavez Ave Ste 204,34.061278,-118.246224,90012,CA
1,KIPP LA Schools (School Support Center),Building,445 S Figueroa St,34.053511,-118.257228,90071,CA
2,California Charter Schools Association,Office,250 E 1st St,34.050241,-118.241227,90012,CA
3,Alliance College-Ready Public Schools,School,601 S Figueroa St,34.050896,-118.259423,90017,CA
4,Imagine Schools on Superior,Elementary School,NaN,34.053050,-118.255604,90071,CA
5,Greendot Public Schools HQ,None,350 S Figueroa St,34.053865,-118.253772,90071,CA
6,Frederick K.C. Price III Schools,Elementary School,7901 S Vermont Ave,33.968144,-118.295557,90044,CA
7,MLA Partner Schools,None,1035 S Grand Ave,34.041697,-118.261585,90015,CA
8,Green Dot Public Schools Office,Office,1149 S Hill St Ste 600,34.039209,-118.261451,90015,CA
9,Families in Schools,Non-Profit,1545 Wilshire Blvd,34.055862,-118.269207,90017,CA
10,Robert F. Kennedy Community Schools,College Classroom,3400 Wilshire Blvd,34.059576,-118.296155,90010,CA
11,The Partnership for Los Angeles Schools,None,1541 Wilshire Blvd,34.055549,-118.270161,90017,CA
12,School studying,College Technology Building,NaN,34.044651,-118.244972,NaN,CA
13,Loyola Law School Shuttle Stop,Bus Line,NaN,34.049936,-118.259666,NaN,California
14,Solano School Stairs,Trail,NaN,34.075977,-118.231651,NaN,CA
15,Contractors State License Schools,Trade School,2750 Colorado Blvd,34.142498,-118.225615,90041,CA
16,Loyola Law School Shuttle,Bus Line,NaN,34.048978,-118.270549,NaN,CA
17,Nationwide Real Estate Schools,Trade School,6725 W Sunset Blvd,34.098580,-118.337226,90028,CA
18,UCLA Community School,School,3201 W 8th St,34.058373,-118.298300,90005,CA
19,CA DMV Approved Traffic Schools,Driving School,6399 Wilshire Blvd Suite 209,34.063539,-118.370980,90048,CA
20,City of Angels School Sunrise Site,High School,963 South Euclid,34.029448,-118.208461,NaN,CA
21,Nationwide Real Estate Executives,Trade School,1968 W Adams Blvd,34.032399,-118.308159,90018,CA
22,Mount Washington Elementary School Stairs,Trail,NaN,34.105056,-118.215030,NaN,CA
23,California Driving School search,Auto Dealership,"11 W Pomona Blvd, Monterey Park, CA 91754, USA",34.033584,-118.130109,91754,CA
24,After School Special,Food Truck,NaN,34.062370,-118.357092,90036,CA

In [20]:
clean_School_dataframe3 = clean_School_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_School_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,LA Schools Federal Credit Union,Credit Union,701 W Cesar E Chavez Ave Ste 204,34.061278,-118.246224,90012,CA
1,KIPP LA Schools (School Support Center),Building,445 S Figueroa St,34.053511,-118.257228,90071,CA
2,California Charter Schools Association,Office,250 E 1st St,34.050241,-118.241227,90012,CA
3,Alliance College-Ready Public Schools,School,601 S Figueroa St,34.050896,-118.259423,90017,CA
6,Frederick K.C. Price III Schools,Elementary School,7901 S Vermont Ave,33.968144,-118.295557,90044,CA
8,Green Dot Public Schools Office,Office,1149 S Hill St Ste 600,34.039209,-118.261451,90015,CA
9,Families in Schools,Non-Profit,1545 Wilshire Blvd,34.055862,-118.269207,90017,CA
10,Robert F. Kennedy Community Schools,College Classroom,3400 Wilshire Blvd,34.059576,-118.296155,90010,CA
15,Contractors State License Schools,Trade School,2750 Colorado Blvd,34.142498,-118.225615,90041,CA
17,Nationwide Real Estate Schools,Trade School,6725 W Sunset Blvd,34.098580,-118.337226,90028,CA
18,UCLA Community School,School,3201 W 8th St,34.058373,-118.298300,90005,CA
19,CA DMV Approved Traffic Schools,Driving School,6399 Wilshire Blvd Suite 209,34.063539,-118.370980,90048,CA
21,Nationwide Real Estate Executives,Trade School,1968 W Adams Blvd,34.032399,-118.308159,90018,CA
23,California Driving School search,Auto Dealership,"11 W Pomona Blvd, Monterey Park, CA 91754, USA",34.033584,-118.130109,91754,CA

In [21]:
df_School = clean_School_dataframe3[clean_School_dataframe3.categories == 'School']
df_School

,name,categories,address,lat,lng,postalCode,state
3,Alliance College-Ready Public Schools,School,601 S Figueroa St,34.050896,-118.259423,90017,CA
18,UCLA Community School,School,3201 W 8th St,34.058373,-118.298300,90005,CA

## Search Query For Entertainment

In [47]:
# search for Entertainment
search_query = 'Entertainment'
radius = 1000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0&client_secret=RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ&ll=34.0536909,-118.2427666&v=20180604&query=Entertainment&radius=1000&limit=30'

In [48]:
eresults = requests.get(url).json()

In [49]:
venues = eresults['response']['venues']

# tranform venues into a dataframe
Entertainment_dataframe = json_normalize(venues)
Entertainment_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'id': '4bf58dd8d48988d1f1931735', 'name': 'G...",False,56424e88498eecf2b913f332,NaN,US,Los Angeles,United States,NaN,137,"[Los Angeles, CA, United States]","[{'label': 'display', 'lat': 34.0532816554229,...",34.053282,-118.244176,NaN,CA,Papillons Entertainment,v-1565101443,NaN
1,"[{'id': '4bf58dd8d48988d1f2931735', 'name': 'P...",False,57a4d72f498e9c85e9a37796,NaN,US,Los Angeles,United States,NaN,226,"[Los Angeles, CA, United States]","[{'label': 'display', 'lat': 34.05214385256302...",34.052144,-118.244358,NaN,CA,Art Deco Entertainment,v-1565101443,226248546
2,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",False,52d6e3b5498e17ec1eb53348,205 S Broadway,US,Los Angeles,United States,2nd St.,370,"[205 S Broadway (2nd St.), Los Angeles, CA 900...","[{'label': 'display', 'lat': 34.05351625661037...",34.053516,-118.246778,90012,CA,Superbot Entertainment,v-1565101443,NaN
3,"[{'id': '50328a8e91d4c4b30a586d6c', 'name': 'N...",False,5111e08f582f91219e7e6798,"201 West 5th Street, Suite T-700",US,Los Angeles,United States,NaN,926,"[201 West 5th Street, Suite T-700, Los Angeles...","[{'label': 'display', 'lat': 34.04766360536331...",34.047664,-118.249691,90017,CA,CTAOP - Entertainment Industry Foundation,v-1565101443,NaN
4,"[{'id': '4bf58dd8d48988d11a941735', 'name': 'O...",False,4efb1463754a3a35a18f2d2f,333 S Hope St #2410,US,Los Angeles,United States,NaN,961,"[333 S Hope St #2410, Los Angeles, CA 90071, U...","[{'label': 'display', 'lat': 34.05401055235499...",34.054011,-118.253188,90071,CA,Fantasy Entertainment,v-1565101443,NaN

In [50]:
# keep only columns that include venue name, and anything that is associated with location
Entertainment_clean_columns = ['name', 'categories'] + [col for col in Entertainment_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Entertainment_dataframe = Entertanment_dataframe.loc[:,Entertainment_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list5 = row['categories']
    except:
        categories_list5 = row['venue.categories']
        
    if len(categories_list5) == 0:
        return None
    else:
        return categories_list5[0]['name']

# filter the category for each row
clean_Entertainment_dataframe['categories'] = clean_Entertainment_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Entertainment_dataframe.columns = [column.split('.')[-1] for column in clean_Entertainment_dataframe.columns]

clean_Entertainment_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,Papillons Entertainment,General Entertainment,NaN,US,Los Angeles,United States,NaN,137,"[Los Angeles, CA, United States]","[{'label': 'display', 'lat': 34.0532816554229,...",34.053282,-118.244176,NaN,CA,56424e88498eecf2b913f332
1,Art Deco Entertainment,Performing Arts Venue,NaN,US,Los Angeles,United States,NaN,226,"[Los Angeles, CA, United States]","[{'label': 'display', 'lat': 34.05214385256302...",34.052144,-118.244358,NaN,CA,57a4d72f498e9c85e9a37796
2,Superbot Entertainment,Office,205 S Broadway,US,Los Angeles,United States,2nd St.,370,"[205 S Broadway (2nd St.), Los Angeles, CA 900...","[{'label': 'display', 'lat': 34.05351625661037...",34.053516,-118.246778,90012,CA,52d6e3b5498e17ec1eb53348
3,CTAOP - Entertainment Industry Foundation,Non-Profit,"201 West 5th Street, Suite T-700",US,Los Angeles,United States,NaN,926,"[201 West 5th Street, Suite T-700, Los Angeles...","[{'label': 'display', 'lat': 34.04766360536331...",34.047664,-118.249691,90017,CA,5111e08f582f91219e7e6798
4,Fantasy Entertainment,Other Nightlife,333 S Hope St #2410,US,Los Angeles,United States,NaN,961,"[333 S Hope St #2410, Los Angeles, CA 90071, U...","[{'label': 'display', 'lat': 34.05401055235499...",34.054011,-118.253188,90071,CA,4efb1463754a3a35a18f2d2f

## Dropping the Irrelevant Columns in Entertainment Dataset

In [52]:
# delete unnecessary columns
clean_Entertainment_dataframe2= clean_Entertainment_dataframe.drop(['cc', 'city', 'country','crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_Entertainment_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Papillons Entertainment,General Entertainment,NaN,34.053282,-118.244176,NaN,CA
1,Art Deco Entertainment,Performing Arts Venue,NaN,34.052144,-118.244358,NaN,CA
2,Superbot Entertainment,Office,205 S Broadway,34.053516,-118.246778,90012,CA
3,CTAOP - Entertainment Industry Foundation,Non-Profit,"201 West 5th Street, Suite T-700",34.047664,-118.249691,90017,CA
4,Fantasy Entertainment,Other Nightlife,333 S Hope St #2410,34.054011,-118.253188,90071,CA
5,Live Entertainment Network HQ,Tech Startup,448 S Hill St,34.048800,-118.251408,90013,CA
6,Xlanes Family Entertainment Center,Theme Park,333 S Alameda St,34.044534,-118.238323,90013,CA
7,Brownstone Entertainment,Office,453 S Spring St Fl 12,34.047744,-118.249734,90013,CA

In [53]:
df_Entertainment = clean_Entertainment_dataframe2[clean_Entertainment_dataframe2.categories == 'Office']
df_Entertainment

,name,categories,address,lat,lng,postalCode,state
2,Superbot Entertainment,Office,205 S Broadway,34.053516,-118.246778,90012,CA
7,Brownstone Entertainment,Office,453 S Spring St Fl 12,34.047744,-118.249734,90013,CA

## Search Query for College

In [60]:
search_query = 'College'
radius = 1000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0&client_secret=RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ&ll=34.0536909,-118.2427666&v=20180604&query=College&radius=1000&limit=30'

In [61]:
cresults = requests.get(url).json()

In [65]:
venues = cresults['response']['venues']

# tranform venues into a dataframe
college_dataframe = json_normalize(venues)
college_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'id': '4bf58dd8d48988d1ad941735', 'name': 'T...",False,4dee6b151f6e0f9053fa20c4,Broadway Ave,US,Los Angeles,United States,5th Street,923,"[Broadway Ave (5th Street), Los Angeles, CA 90...","[{'label': 'display', 'lat': 34.04829398880624...",34.048294,-118.250370,90013,CA,LA Barber College,v-1565101840,NaN
1,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",False,4b48a660f964a5209a5126e3,700 W 1st St,US,Los Angeles,United States,at Hope St,738,"[700 W 1st St (at Hope St), Los Angeles, CA 90...","[{'label': 'display', 'lat': 34.05597374706711...",34.055974,-118.250287,90012,CA,Bikram Yoga Downtown LA,v-1565101840,83943050

In [66]:
# keep only columns that include venue name, and anything that is associated with location
college_clean_columns = ['name', 'categories'] + [col for col in college_dataframe.columns if col.startswith('location.')]+ ['id']
clean_college_dataframe = college_dataframe.loc[:,college_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list5 = row['categories']
    except:
        categories_list5 = row['venue.categories']
        
    if len(categories_list5) == 0:
        return None
    else:
        return categories_list5[0]['name']

# filter the category for each row
clean_college_dataframe['categories'] = clean_college_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_college_dataframe.columns = [column.split('.')[-1] for column in clean_college_dataframe.columns]

clean_college_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,LA Barber College,Trade School,Broadway Ave,US,Los Angeles,United States,5th Street,923,"[Broadway Ave (5th Street), Los Angeles, CA 90...","[{'label': 'display', 'lat': 34.04829398880624...",34.048294,-118.250370,90013,CA,4dee6b151f6e0f9053fa20c4
1,Bikram Yoga Downtown LA,Yoga Studio,700 W 1st St,US,Los Angeles,United States,at Hope St,738,"[700 W 1st St (at Hope St), Los Angeles, CA 90...","[{'label': 'display', 'lat': 34.05597374706711...",34.055974,-118.250287,90012,CA,4b48a660f964a5209a5126e3

## Dropping the Columns from college Data Frame

In [67]:
clean_college_dataframe2= clean_college_dataframe.drop(['cc', 'city', 'country','crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_college_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,LA Barber College,Trade School,Broadway Ave,34.048294,-118.250370,90013,CA
1,Bikram Yoga Downtown LA,Yoga Studio,700 W 1st St,34.055974,-118.250287,90012,CA

In [70]:
df_college = clean_college_dataframe2[clean_college_dataframe2.categories == 'Trade School']
df_college

,name,categories,address,lat,lng,postalCode,state
0,LA Barber College,Trade School,Broadway Ave,34.048294,-118.25037,90013,CA

## Search Query For Parks

In [71]:
search_query = 'parks'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4FQQJE2LMGVLERRRE2BOFR1LQQR5ZEHFLTD1WRAFKOFT4TI0&client_secret=RCSNR5TH31NQRG2QYCHK101HRMTUZHBB2TSJ1CJU5UOGRXRQ&ll=34.0536909,-118.2427666&v=20180604&query=parks&radius=10000&limit=30'

In [72]:
presults = requests.get(url).json()

In [73]:
venues = presults['response']['venues']

# tranform venues into a dataframe
park_dataframe = json_normalize(venues)
park_dataframe.head()

,categories,delivery.id,delivery.provider.icon.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.name,delivery.url,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'id': '4bf58dd8d48988d1df931735', 'name': 'B...",323118,/delivery_provider_grubhub_20180129.png,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",grubhub,https://www.grubhub.com/restaurant/the-parks-f...,False,4e45d32eb0fb93df2701eeb3,1267 W Temple St,US,Los Angeles,United States,at E Edgeware Rd,1780,"[1267 W Temple St (at E Edgeware Rd), Los Ange...","[{'label': 'display', 'lat': 34.06651930066153...",34.066519,-118.254291,90026,CA,The Park's Finest BBQ,v-1565102231,95346544
1,"[{'id': '4bf58dd8d48988d113941735', 'name': 'K...",NaN,NaN,NaN,NaN,NaN,NaN,False,4ad94bbaf964a520a61921e3,955 S Vermont Ave,US,Los Angeles,United States,at W Olympic Blvd,4531,"[955 S Vermont Ave (at W Olympic Blvd), Los An...","[{'label': 'display', 'lat': 34.05391968859168...",34.053920,-118.291902,90006,CA,Park's BBQ,v-1565102231,85786107
2,"[{'id': '4c38df4de52ce0d596b336e1', 'name': 'P...",NaN,NaN,NaN,NaN,NaN,NaN,False,4d850305f9f3a1cdc698c264,539-699 N Alameda St,US,Los Angeles,United States,NaN,493,"[539-699 N Alameda St, Los Angeles, CA 90012, ...","[{'label': 'display', 'lat': 34.05364421914453...",34.053644,-118.237412,90012,CA,Joe's 414 Auto Parks Public Parking,v-1565102231,NaN
3,"[{'id': '4d954b16a243a5684b65b473', 'name': 'R...",NaN,NaN,NaN,NaN,NaN,NaN,False,50895ce0e4b0db48d79b0649,237 S San Pedro St,US,Los Angeles,United States,NaN,120,"[237 S San Pedro St, Los Angeles, CA 90012, Un...","[{'label': 'display', 'lat': 34.0532701, 'lng'...",34.053270,-118.241567,90012,CA,Joe's Auto Parks Lot #242,v-1565102231,NaN
4,"[{'id': '4c38df4de52ce0d596b336e1', 'name': 'P...",NaN,NaN,NaN,NaN,NaN,NaN,False,4e36b729ae60d86c3acc57b4,233 S Main St,US,Los Angeles,United States,btwn 2nd & 3rd St,412,"[233 S Main St (btwn 2nd & 3rd St), Los Angele...","[{'label': 'display', 'lat': 34.0506308788914,...",34.050631,-118.245281,90012,CA,Joe's Auto Parks,v-1565102231,NaN

In [74]:
# keep only columns that include venue name, and anything that is associated with location
park_clean_columns = ['name', 'categories'] + [col for col in park_dataframe.columns if col.startswith('location.')]+ ['id']
clean_park_dataframe = park_dataframe.loc[:,park_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list5 = row['categories']
    except:
        categories_list5 = row['venue.categories']
        
    if len(categories_list5) == 0:
        return None
    else:
        return categories_list5[0]['name']

# filter the category for each row
clean_park_dataframe['categories'] = clean_park_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_park_dataframe.columns = [column.split('.')[-1] for column in clean_park_dataframe.columns]

clean_park_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,The Park's Finest BBQ,BBQ Joint,1267 W Temple St,US,Los Angeles,United States,at E Edgeware Rd,1780,"[1267 W Temple St (at E Edgeware Rd), Los Ange...","[{'label': 'display', 'lat': 34.06651930066153...",34.066519,-118.254291,90026,CA,4e45d32eb0fb93df2701eeb3
1,Park's BBQ,Korean Restaurant,955 S Vermont Ave,US,Los Angeles,United States,at W Olympic Blvd,4531,"[955 S Vermont Ave (at W Olympic Blvd), Los An...","[{'label': 'display', 'lat': 34.05391968859168...",34.053920,-118.291902,90006,CA,4ad94bbaf964a520a61921e3
2,Joe's 414 Auto Parks Public Parking,Parking,539-699 N Alameda St,US,Los Angeles,United States,NaN,493,"[539-699 N Alameda St, Los Angeles, CA 90012, ...","[{'label': 'display', 'lat': 34.05364421914453...",34.053644,-118.237412,90012,CA,4d850305f9f3a1cdc698c264
3,Joe's Auto Parks Lot #242,Rest Area,237 S San Pedro St,US,Los Angeles,United States,NaN,120,"[237 S San Pedro St, Los Angeles, CA 90012, Un...","[{'label': 'display', 'lat': 34.0532701, 'lng'...",34.053270,-118.241567,90012,CA,50895ce0e4b0db48d79b0649
4,Joe's Auto Parks,Parking,233 S Main St,US,Los Angeles,United States,btwn 2nd & 3rd St,412,"[233 S Main St (btwn 2nd & 3rd St), Los Angele...","[{'label': 'display', 'lat': 34.0506308788914,...",34.050631,-118.245281,90012,CA,4e36b729ae60d86c3acc57b4

## Dropping the Irrelevant Columns

In [75]:
clean_park_dataframe2= clean_park_dataframe.drop(['cc', 'city', 'country','crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_park_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,The Park's Finest BBQ,BBQ Joint,1267 W Temple St,34.066519,-118.254291,90026,CA
1,Park's BBQ,Korean Restaurant,955 S Vermont Ave,34.053920,-118.291902,90006,CA
2,Joe's 414 Auto Parks Public Parking,Parking,539-699 N Alameda St,34.053644,-118.237412,90012,CA
3,Joe's Auto Parks Lot #242,Rest Area,237 S San Pedro St,34.053270,-118.241567,90012,CA
4,Joe's Auto Parks,Parking,233 S Main St,34.050631,-118.245281,90012,CA
5,Western National Parks Center,National Park,NaN,34.056051,-118.239045,90012,CA
6,Joe's 433 Auto Parks,Parking,NaN,34.047279,-118.248138,NaN,CA
7,Los Angeles Dept of Rec and Parks,Government Building,221 N Figueroa St,34.058859,-118.250809,90012,CA
8,Joe's 746 Auto Parks,Auto Garage,746 S Hope St,34.046861,-118.258310,90017,CA
9,Park's Cleaners at Grand Promenade,Laundry Service,"225 S Grand Ave, Los Angeles, CA 90012",34.052722,-118.251774,90012,CA
10,joe's auto parks 220,Parking,NaN,34.048029,-118.240850,NaN,CA
11,Olympic Park's Convenience Store,Liquor Store,3533 W Olympic Blvd,34.052700,-118.315742,90019,CA
12,City of Montebello - Parks Admin.,Government Building,1700 W Victoria Ave,34.021345,-118.116397,90640,CA
13,Joe's Auto Parks,Parking,NaN,34.046038,-118.250792,NaN,CA
14,California State Parks Foundation,None,448 S Hill St,34.049526,-118.251084,90013,CA
15,Joe's Auto Parks,Road,NaN,34.048267,-118.249986,90013,CA
16,joe's auto parks 558,Parking,NaN,34.045761,-118.249413,NaN,CA
17,City of Los Angeles: Dept. of Recreation & Parks,Government Building,NaN,34.058906,-118.251483,90012,CA
18,Parks Hot Dogs,Food,614 E 7th St,34.040138,-118.246068,90021,CA
19,Joe's Auto Parks 724,Parking,NaN,34.047532,-118.260922,NaN,CA
20,Joe’s Auto Parks 953,Parking,NaN,34.041469,-118.257725,90015,CA
21,Grand Park Downtown Farmers Market,Farmers Market,First Street (Civic Center),34.052374,-118.244716,90012,CA
22,Joe's Auto Parks 913,General Travel,NaN,34.046508,-118.263297,90015,CA
23,Park's Liquor,Liquor Store,3554 Beverly Blvd,34.073905,-118.285945,90004,CA
24,Parks Tire and Auto Care,Automotive Shop,1632 Venice Blvd,34.044051,-118.289664,90006,CA
25,Joe's Auto Parks 1220,Parking,1248 S Figueroa St,34.041417,-118.266706,90015,CA
26,LA City Department of Aging,Government Building,221 N Figueroa St Ste 500,34.059257,-118.251086,90012,CA
27,Around The World In 80 Days,Bike Rental / Bike Share,NaN,34.050668,-118.250442,97114,CA
28,Dept. Of Parks & Recreation,Government Building,510 S Vermont Ave,34.065184,-118.291072,90020,CA
29,Parks,Basketball Court,2221 Pico Blvd,34.059494,-118.377470,90404,CA

In [79]:
df_park = clean_park_dataframe2[clean_park_dataframe2.categories == 'Parking']
df_park

,name,categories,address,lat,lng,postalCode,state
2,Joe's 414 Auto Parks Public Parking,Parking,539-699 N Alameda St,34.053644,-118.237412,90012,CA
4,Joe's Auto Parks,Parking,233 S Main St,34.050631,-118.245281,90012,CA
6,Joe's 433 Auto Parks,Parking,NaN,34.047279,-118.248138,NaN,CA
10,joe's auto parks 220,Parking,NaN,34.048029,-118.240850,NaN,CA
13,Joe's Auto Parks,Parking,NaN,34.046038,-118.250792,NaN,CA
16,joe's auto parks 558,Parking,NaN,34.045761,-118.249413,NaN,CA
19,Joe's Auto Parks 724,Parking,NaN,34.047532,-118.260922,NaN,CA
20,Joe’s Auto Parks 953,Parking,NaN,34.041469,-118.257725,90015,CA
25,Joe's Auto Parks 1220,Parking,1248 S Figueroa St,34.041417,-118.266706,90015,CA

## Concatenating all the Dataframes

In [80]:
neighbourhood_df = pd.concat([hotel_dataframe,df_School,df_Entertainment,df_college,df_park], ignore_index=True)
neighbourhood_df

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
1,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
2,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
3,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA
4,Alliance College-Ready Public Schools,School,601 S Figueroa St,34.050896,-118.259423,90017,CA
5,UCLA Community School,School,3201 W 8th St,34.058373,-118.298300,90005,CA
6,Superbot Entertainment,Office,205 S Broadway,34.053516,-118.246778,90012,CA
7,Brownstone Entertainment,Office,453 S Spring St Fl 12,34.047744,-118.249734,90013,CA
8,LA Barber College,Trade School,Broadway Ave,34.048294,-118.250370,90013,CA
9,Joe's 414 Auto Parks Public Parking,Parking,539-699 N Alameda St,34.053644,-118.237412,90012,CA
10,Joe's Auto Parks,Parking,233 S Main St,34.050631,-118.245281,90012,CA
11,Joe's 433 Auto Parks,Parking,NaN,34.047279,-118.248138,NaN,CA
12,joe's auto parks 220,Parking,NaN,34.048029,-118.240850,NaN,CA
13,Joe's Auto Parks,Parking,NaN,34.046038,-118.250792,NaN,CA
14,joe's auto parks 558,Parking,NaN,34.045761,-118.249413,NaN,CA
15,Joe's Auto Parks 724,Parking,NaN,34.047532,-118.260922,NaN,CA
16,Joe’s Auto Parks 953,Parking,NaN,34.041469,-118.257725,90015,CA
17,Joe's Auto Parks 1220,Parking,1248 S Figueroa St,34.041417,-118.266706,90015,CA

## Generate map to visualize neighbourhood

In [83]:

hotel_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(neighbourhood_df['lat'], neighbourhood_df['lng'], 
                                                 neighbourhood_df['name'], neighbourhood_df['categories'],\
                                                 neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(hotel_map)  
    
hotel_map

## Generate map to visualize neighbourhood including all dataframes

In [84]:
Tneighbourhood_df = pd.concat([hotel_dataframe,df_School,df_Entertainment,df_college,df_park], ignore_index=True)
Tneighbourhood_df

,name,categories,address,lat,lng,postalCode,state
0,Miyako Hotel,Hotel,328 E 1st St,34.049749,-118.240111,90012,CA
1,Kawada Hotel,Hotel,200 S Hill St,34.052870,-118.247909,90012,CA
2,DoubleTree by Hilton Los Angeles Downtown,Hotel,120 South Los Angeles Street,34.050352,-118.242768,90012,CA
3,Little Toyko Hotel,Hotel,327 1/2 E 1st St,34.050409,-118.240011,90012,CA
4,Alliance College-Ready Public Schools,School,601 S Figueroa St,34.050896,-118.259423,90017,CA
5,UCLA Community School,School,3201 W 8th St,34.058373,-118.298300,90005,CA
6,Superbot Entertainment,Office,205 S Broadway,34.053516,-118.246778,90012,CA
7,Brownstone Entertainment,Office,453 S Spring St Fl 12,34.047744,-118.249734,90013,CA
8,LA Barber College,Trade School,Broadway Ave,34.048294,-118.250370,90013,CA
9,Joe's 414 Auto Parks Public Parking,Parking,539-699 N Alameda St,34.053644,-118.237412,90012,CA
10,Joe's Auto Parks,Parking,233 S Main St,34.050631,-118.245281,90012,CA
11,Joe's 433 Auto Parks,Parking,NaN,34.047279,-118.248138,NaN,CA
12,joe's auto parks 220,Parking,NaN,34.048029,-118.240850,NaN,CA
13,Joe's Auto Parks,Parking,NaN,34.046038,-118.250792,NaN,CA
14,joe's auto parks 558,Parking,NaN,34.045761,-118.249413,NaN,CA
15,Joe's Auto Parks 724,Parking,NaN,34.047532,-118.260922,NaN,CA
16,Joe’s Auto Parks 953,Parking,NaN,34.041469,-118.257725,90015,CA
17,Joe's Auto Parks 1220,Parking,1248 S Figueroa St,34.041417,-118.266706,90015,CA

In [85]:
# Generate map to visualize park neighbourhood including Restaurant and Cafeteria 
park_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(Tneighbourhood_df['lat'], Tneighbourhood_df['lng'], 
                                           Tneighbourhood_df['name'], Tneighbourhood_df['categories'],\
                                               Tneighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(park_map)  
    
park_map

#### Note: Made it very Simple since I have very less time to explore time places.